### ISSUE TITLE
Add CI builds to improve pull request and code quality

### ISSUE THREAD

**Issue by jeking3** [boostorg/program_options#43]
CI builds would run every pull request and periodically run master and develop through builds to prove out code correctness (i.e. does it compile, link, and pass unit tests?) as well as code coverage and static code analysis (coverity scan, cppcheck, ubsan jobs).

There are good examples in the Boost.DateTime, Boost.Format, and Boost.Uuid repositories on how to set these up.  I can assist in setting these up if needed.

**Comment by vprus** [comment]
CI is an obviously good idea, and if you provide a PR that adds support I'd be happy to merge it. (Personally, I lost track which of the multiple solutions is considered best for Boost)

**Comment by jeking3** [comment]
One (PR) is forthcoming.  Should be today.

Also, there are 90 open issues in Boost Trac going back to version 1.40.0 that need to be scrubbed.  Based on my experience with other repositories, chances are that a good percentage are already fixed.  https://svn.boost.org/trac10/query?status=!closed&component=program_options
