### ISSUE TITLE
Builds on cygwin (32 and 64-bit) fail due to missing putenv() definition

### ISSUE THREAD

**Issue by jeking3** [boostorg/program_options#45]
Likely a missing include or macro in the build environment.  Identified with new CI build suite.
See: https://ci.appveyor.com/project/jeking3/program-options/build/job/6cwpgdbjt75iw334

```
libs\program_options\test\parsers_test.cpp: In function 'void test_environment()':
674libs\program_options\test\parsers_test.cpp:255:46: error: 'putenv' was not declared in this scope
675     putenv(const_cast<char*>("PO_TEST_FOO=1"));
676                                              ^
677
678    "g++"   -std=c++03 -m64 -O0 -fno-inline -Wall -g  -DBOOST_ALL_NO_LIB=1  -I"." -c -o "bin.v2\libs\program_options\test\parsers_test.test\gcc-6.4.0\debug\cxxstd-03-iso\link-static\target-os-cygwin\parsers_test.o" "libs\program_options\test\parsers_test.cpp"
679
680...failed gcc.compile.c++ bin.v2\libs\program_options\test\parsers_test.test\gcc-6.4.0\debug\cxxstd-03-iso\link-static\target-os-cygwin\parsers_test.o...
```

**Comment by teeks99** [comment]
I see that CI was added for appoveyor for cygwin and mingw but they don't seem to be passing. Was the point of that merge to show this bug?

**Comment by vprus** [comment]
Thanks for the report! Unfortunately, the last time I used Cygwin was about 20 years ago, so I won't be able to fix this problem - but will appreciate patches.

**Comment by pdimov** [comment]
Fixed in https://github.com/boostorg/program_options/commit/d1ddaa8a0eca167db6669f42ff57f478500ca323.
