### ISSUE TITLE
Cannot use shared library in C++98

### ISSUE THREAD

**Issue by jbeich** [boostorg/program_options#65]
After https://github.com/boostorg/function/pull/25 building a C++ < 11 consumer fails. Affects at least [gearmand](https://ptpb.pw/C_HL), [pdfedit](https://ptpb.pw/98Fg), [uhd](https://ptpb.pw/oVqK). CC @Kojoley

```c++
$ cat >a.cc
#include <boost/program_options.hpp>

int main(int argc, char **argv) {
  boost::program_options::options_description desc("foo");
  boost::program_options::parse_command_line(argc, argv, desc);
  return 0;
}

$ c++ -std=gnu++98 a.cc -lboost_program_options
>>> referenced by a.cc
>>>               /tmp/a-fa8c69.o:(boost::program_options::basic_command_line_parser<char>::extra_parser(boost::function1<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>))
c++: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Kojoley** [comment]
It is not a surprise I was mentioned the roots of the problem in https://github.com/boostorg/function/pull/25#issuecomment-431603996.

**Comment by Kojoley** [comment]
It looks like the actual problem is not even boost::function change, but https://github.com/boostorg/parameter/commit/fb88905a99031d5f041ce4592c94743dfbf7259a

**Comment by Kojoley** [comment]
Can you try to revert #25 locally and check with the latest boost::parameter? It looks like the actual problem is not even #25 change, but https://github.com/boostorg/parameter/commit/fb88905a99031d5f041ce4592c94743dfbf7259a (boost::parameter now uses `std::function` when it is available).

**Comment by jbeich** [comment]
Reverting boostorg/function#25 does help. It was the first thing I've tried.

**Comment by jbeich** [comment]
After 99727ac7104b Boost itself [fails to build](https://ptpb.pw/EHY5):
```c++
In file included from libs/program_options/src/options_description.cpp:13:
./boost/program_options/parsers.hpp:172:38: error: too few template arguments for class template 'pair'
                       function<std::pair<std::string(std::string)>,
                                     ^
./boost/container/detail/std_fwd.hpp:39:8: note: template is declared here
struct pair;
       ^
In file included from libs/program_options/src/options_description.cpp:13:
./boost/program_options/parsers.hpp:173:54: error: no viable conversion from 'boost::program_options::ext_parser' (aka 'function<pair<basic_string<char, char_traits<char>, allocator<char> >, basic_string<char, char_traits<char>, allocator<char> > > (const basic_string<char, char_traits<char>, allocator<char> > &)>') to 'int'
                                 const std::string&> ext
                                                     ^
./boost/function/function_template.hpp:955:5: note: candidate function
    operator safe_bool () const
    ^
./boost/program_options/parsers.hpp:173:54: note: passing argument to parameter 'ext' here
                                 const std::string&> ext
                                                     ^
2 errors generated.
```

**Comment by vprus** [comment]
Replacing `function1` with `function` does not seem an appropriate fix for me. Sure, it might fix program_options, however it suggests that existing code using functionN will break, which I find rather undesirable, and IIUC it's not the behaviour that @pdimov wanted either.

**Comment by Kojoley** [comment]
>  it suggests that existing code using functionN will break

I do not understand why `functionN` still is not deprecated and used in boost libraries. There is no compilers on regression matrix that does not support partial template specialization. It is a straightforward fix to existing code to migrate to `function` and it only needed for the user who still uses `functionN`.

On the other hand, the problem is that @jbeich uses libraries compiled with C++11 with C++03 apps. I do not think we should bother about this case anymore.

**Comment by jbeich** [comment]
@Kojoley, after fixing a typo in 99727ac7104b C++98 example and the affected consumers ([gearmand](https://ptpb.pw/VAGt), [pdfedit](https://ptpb.pw/Ba1X), [uhd](https://ptpb.pw/KEaP)) build fine. Testing all Boost consumers for regressions downstream (~400 packages) may take more time.

**Comment by pdimov** [comment]
It's probably best to revert the Function change for now.
